require("core.lazy")
require("core.config")
require("core.keymaps")
require("core.colors")

require("plugins.neo-tree")
require("plugins.treesitter")
require("plugins.lsp")
require("plugins.cmp")
require("plugins.modicator")
