-- return {
--     {
--         "ahmedkhalf/project.nvim",
--         event = { "VimEnter" },
--         config = function()
--             require("project_nvim").setup({
--                 detection_methods = { "pattern" },
--                 patterns = { ".git", "src" },
--             })
--         end,
--     },
-- }
